language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy ./reverseproxy
  - docker tag reverseproxy omugwane/reverseproxy:latest
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user omugwane/udagram-api-user:latest
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed omugwane/udagram-api-feed:latest
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend omugwane/udagram-frontend:latest


# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  -  docker push omugwane/udagram-api-feed:latest
  -  docker push omugwane/udagram-api-user:latest
  -  docker push omugwane/reverseproxy:latest
  -  docker push omugwane/udagram-frontend:latest