apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: udagram-api-user
        image: omugwane/udagram-api-user:v2
        ports:
        - containerPort: 8080
        
        env:
       # Define the environment variable
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
               name: udagram-dev-env
               key: AWS_BUCKET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: udagram-dev-env
              key: POSTGRES_DB

        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: udagram-dev-env
              key: POSTGRES_HOST
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: udagram-dev-env
              key: AWS_REGION

        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: udagram-dev-env
              key: AWS_PROFILE

        - name: URL
          valueFrom:
            configMapKeyRef:
              name: udagram-dev-env
              key: URL

        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: mypgsecre
              key: POSTGRES_USERNAME

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mypgsecre
              key: POSTGRES_PASSWORD